server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Para que el enrutamiento de React (React Router) funcione sin dar error 404
        try_files $uri $uri/ /index.html;
    }
}
